fix path as tag names has changed from %{version} to %{name}-%{version}
fixing:
$ rpmbuild -ba SPECS/5minute.spec
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.vMa5kR
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ cd /home/user/rpmbuild/BUILD
+ rm -rf 5minute-0.2.31
+ /usr/bin/gzip -dc /home/user/rpmbuild/SOURCES/5minute-0.2.31.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd 5minute-0.2.31
/var/tmp/rpm-tmp.vMa5kR: line 40: cd: 5minute-0.2.31: No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.vMa5kR (%prep)